child_meal_price = float(input("What is the price of a child's meal? "))
adult_meal_price = float(input("What is the price of an adult's meal? "))
children = int(input('How many children are there? '))
adult = int(input('How many adults are there? '))
drinks = int(input('How many drinks? '))
drink_price = float(input('What is the price of a drink? '))
sales_tax_rate = float(input('What is the sales tax rate? '))
subtotal = round(child_meal_price * children + adult_meal_price * adult_meal_price + drinks * drink_price ,2)
print (f'Subtotal: ${subtotal}')
sales_tax = round((subtotal * sales_tax_rate) / (100),2)
print (f'Sales Tax = ${sales_tax}')
total = round(subtotal + sales_tax,2)
print (f'Total: ${total}')
print ()
payment_amount = float(input('What is the payment amount? '))
change = round(payment_amount - total,2)
print (f'Change: ${change}')
